### ISSUE TITLE
error happens when run train.py

### ISSUE THREAD

**Issue by BrightMoonStar** [UT-Austin-RPL/maple#8]
When I run train.py, an error happened. Could you please give some suggestions? Thank you very much !

```
Traceback (most recent call last):
  File "/home/xxx/Videos/bin/boot/maple/scripts/train.py", line 247, in <module>
    run_experiment(
  File "/home/xxx/Videos/bin/boot/maple/maple/launchers/launcher_util.py", line 593, in run_experiment
    return run_experiment_here(
  File "/home/xxx/Videos/bin/boot/maple/maple/launchers/launcher_util.py", line 168, in run_experiment_here
    return experiment_function(variant)
  File "/home/xxx/Videos/bin/boot/maple/maple/launchers/robosuite_launcher.py", line 51, in experiment
    expl_env = make_env(mode='expl')
  File "/home/xxx/Videos/bin/boot/maple/maple/launchers/robosuite_launcher.py", line 36, in make_env
    env = suite.make(
  File "/home/xxx/anaconda3/envs/TD/lib/python3.9/site-packages/robosuite/environments/base.py", line 40, in make
    return REGISTERED_ENVS[env_name](*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'table_offset'
```

**Comment by youmehave** [comment]
Hello, I also encounter the same error, but I suffer description of error is "TypeError: __init__() got an unexpected keyword argument 'skill_config'". Could you please give some suggestions? Thank you very much!

**Comment by zlm200** [comment]
I'm also having the same two issues, can you please fix it？
